spring:
  application:
    name: display

server:
  port: 8081

hystrix:
  command:
    default:    # command key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

