server:
  port: 8762  # Default : 8761

spring:
  application:
    name: vine-eureka

eureka:
  server:
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true                 # Use ip address instead of hostname from OS when reporting myself to eureka server

